exclude: ['vendor']
include: ['_pages', '_pages/film', '_pages/writing', 'pages/photography']

title:            Teagan The Bootblack
email:            tkwidmer@gmail.com
blog_title:       A Shine of Bootblacks
tagline:          Oakland Based Bootblack
url:              http://www.teaganwidmer.me
paginate:         1
author:
  name:           Teagan Widmer
  url:            https://www.teaganwidmer.me
  email:          tkwidmer@gmail.com
  twitter:        https://twitter.com/twidx

# Site settings
description: > # this means to ignore newlines until "baseurl:"
  Teagan Widmer is a software engineer, writer, artist and activist from San Francisco.
  She writes about feminism, diveristy in tech, and the lgbt community.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leather.teaganwidmer.me" # the base hostname & protocol for your site
twitter_username: teaganBootblack
github_username:  tkwidmer

collections:
  galleries:
    output: true

# Build settings
pages: ./_pages
markdown: kramdown


social_links:
  - icon: fa-twitter
    url: http://www.twitter.com/twidx
  - icon: fa-github
    url: http://www.github.com/tkwidmer

gems:
  - jekyll-redirect-from